CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS knowledge;
CREATE SCHEMA IF NOT EXISTS agent_runtime;
CREATE SCHEMA IF NOT EXISTS private_memory;
CREATE SCHEMA IF NOT EXISTS identity;
